### ISSUE TITLE
Seven Theme - Flash

### ISSUE THREAD

**Issue by BossOfGames** [BossOfGames/phpvms#12]

**Comment by arthurpar06** [comment]
![Image](https://github.com/user-attachments/assets/a5bc59c0-f837-4165-a14e-c95584392080)
![Image](https://github.com/user-attachments/assets/2f0129d2-4f7b-4b39-9d4c-889ca8052e96)

I didn’t update the modal part because I don’t think we ever use it in phpVMS. I couldn’t even manage to trigger this kind of alert.

**Comment by BossOfGames** [comment]
Fair, this could probably stay the same. If we don't have any issues, I'm ok if we close this out if y'all are.
